F1:
    outputs:
        duckdb:
            type: duckdb
            #            schema: F1
            schema: main
            path: ./data.duckdb
        sqlite:
            type: sqlite
            host: localhost
            threads: 1
            database: "database"
            schema: "main"
            schemas_and_paths:
                main: sqlite/sqlite.db
            schema_directory: sqlite
        dev:
            dbname: postgres
            host: localhost
            pass: S3cret
            port: 5432
            schema: public
            threads: 1
            type: postgres
            user: postgres
    target: duckdb
